# Use official Python image
FROM python:3.11-slim

WORKDIR /script

# Copy files
COPY . /script

# Install dependencies
RUN pip install -r requirements.txt

# Run the app
CMD ["python", "metric-scripts.py"]